version: '2.1'
services:
  postgres:
    image: quay.io/debezium/postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=inventory
    networks:
      - cdc-network

  zookeeper:
    image: quay.io/debezium/zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - cdc-network

  kafka:
    image: quay.io/debezium/kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - cdc-network

  mysql:
    image: quay.io/debezium/example-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - cdc-network

  connect:
    image: debezium/connect:1.8
    ports:
      - 8083:8083
    links:
      - kafka
      - mysql
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    networks:
      - cdc-network

networks:
  cdc-network:
    name: cdc-network
